08-3-temporal_order_classification_experiments_companion.ipynb

Hi @Atcold ,
Thanks again for the lectures at CoDaS-HEP!
This pull request introduces a companion notebook inspired by the temporal sequence classification demo from the last day of the school. I've finally found time to tidy it up, so I hope it adds something to the content here.
If I spouted anything that's wrong or you have some style recommendations, please feel free to make any corrections/modifications as needed, or let me know and I can do it. We can drop the blog-post feel of the notebook too, that's just how I chose to keep it interesting for myself while dealing with a crazy flight schedule...

Companion Notebook to Temporal Sequence RNN Demo

---

01-tensor_tutorial.ipynb
02-space_stretching.ipynb
03-autograd_tutorial.ipynb
04-spiral_classification.ipynb
05-regression.ipynb
06-convnet.ipynb
07-listening_to_kernels.ipynb
09-echo_data.ipynb
10-autoencoder.ipynb
12-regularization.ipynb
plot_lib.py

This PR updates the notebooks to ensure that defined tensors and models are on the proper device.
Note that I chose to enforce operations on the CPU in `plot_lib.py` since this file primarily performs CPU specific operations like `.numpy` and plotting.
This fixes the issue in #6 .

Ensure tensors are on proper device

---

environment.yml

Changed “= torchviz” to “- torchviz”

Fixed torchviz installation

---

plot_lib.py

Fix for https://github.com/Atcold/pytorch-Deep-Learning-Minicourse/issues/11

Fix for TypeError in plot_lib.py (cpu vs cuda)

---

docs/_config.yml

Enable snytax highlighting

---

LICENSE.md

Refer to discussion at: https://github.com/Atcold/SP19-DL-collaborative-notes/issues/104#event-3019015460

Add CC BY-NC-SA license

---

docs/_config.yml

I commented in `_config.yml` on how you can do this, just
uncomment the prologues section and add pages as you desire.

Add the ability to add pages before chapters

---

docs/_config.yml
docs/_includes/macros.html
docs/_layouts
docs/_layouts/default.html
docs/_layouts/withmacros.html
docs/chapters/01-1.md
docs/chapters/01-2.md
docs/chapters/01-3.md
docs/chapters/01.md
docs/chapters/02-1.md
docs/chapters/02-2.md
docs/chapters/02-3.md
docs/chapters/02.md

Please see `_includes/macros.html` for an example - you _have_ to use \gdef
to define the macros, and manually include it in each new file.

Add ability to support macros

---

docs/_config.yml

As you requested, @Atcold, you can now put sections in the prologue and epilogue as well.

Sections in prologue and epilogue

---

docs/chapters/02-1.md
docs/chapters/02-2.md
docs/chapters/02-3.md

This PR revises English grammar and fixes typos from week 2 lecture and recitation. Some minor corrections in the equations are also made.

English Grammar: Week 2 Lecture and Recitation

---

docs/README.md

Update website docs to avoid submodule bugs.

update docs README

---

docs/chapters/03-2.md

My apologies for not being able to spot and fix all typos in one PR. Fixed a wrong gif insertion and more grammar issues in the final conclusion.

Week 3 - Part 2 More Fixes

---

README.md

Add this "A Mandarin translation of this README.md and website can be found here." in Mandarin.

Add one line for translation in README.md

---

docs/_config.yml
docs/chapters/05-1.md
docs/chapters/05.md

Goes over Gradient Descent, SGD and Momentum. Moved Images to a separate folder and tested the website locally.

Optimization Techniques I 05-1

---

docs/chapters/05-1.md

Patch 2:
Adding image source.
Seems like I have to create a new branch (and pull request), every time you merge changes from my remote branch.

Adding Image Source for 05-1

---

docs/en/week02/02-1.md
docs/zh/week02/02-1.md

- Images were not diplaying after updating the locations
- Captions were not centered
- Chinese translation captions were not working correctly because of wrong comment placement
- All the other figures had ':' except figure 2

Some extra fixes for 02-1

---

docs/en/week03/03-3.md

Fix broken image links

---

docs/en/week05/05-2.md

Add extended explanation on batch norm

---

docs/en/week02/02-2.md

Momentum algorithm does not adapt learning rate

Correction in Week 02, Lecture part 2

---

docs/zh/week02/02-2.md

Check #133 for details, it failed to make the relevant change for the Chinese translation.

#133 for the Chinese translation as well

---

docs/es/index.md

Let me know if there is some that still need to be shrink.

Shortened title names on `es/index.md` and removed graders from "People"

---

docs/en/week06/06.md

adding summary for 6.2 lecture

---

README.md
docs/es/index.md

Repaired links at index.md to point correctly to `/es` directory

Added `README-ES.md` link to main README. Also Added flags for each lang.

---

docs/en/week04/04-1.md

Fixed a typo: change ‘understoof’ to ‘understood’.

Typo Fix 04-1.md

---

docs/es/week01/01-1.md
docs/es/week01/01.md
docs/es/week05/05-1.md
docs/es/week05/05.md

For files: 01.md, 01-1.md, 05.md, 05-1.md

Added commented original text before each paragraph.

---

docs/en/week01/01-1.md

Changed the capitalized letters in the equations and fixed some grammar.

Fixing latex

---

docs/_config.yml
docs/es/week01/01-2.md

Evolución y Usos de las CNNs y ¿Por qué Aprendizaje Profundo?

[ES] Translation of 01-2.md

---

docs/en/week08/08-3.md

Changes/fixes from the original pull request - #166

Updates as requested in #166 for Week 8 Lab Notes

---

docs/_config.yml
docs/es/week04/04-1.md
docs/es/week04/04.md

Hi Alf! I send you a pull request with the week 4 traslated. If you need something more tell me.
Regards
Manuel

[ES]Translation of 04, 04-1

---

docs/es/week04/04-1.md

I just translate the names of the figures!!  
Take care of yourself for New York!!! We're living difficult moments.
Regards

Translation of the figures

---

docs/es/week01/01-1.md
docs/ko/week01/01-1.md
docs/zh/week01/01-1.md

#144 
Fixed the equations in es, zh and ko. The Italian folder doesn't have the translated file yet.

Fixing latex in all translations

---

docs/en/week08/08-3.md

Fix the paragraph under Reparameterization and the forward function for jupyter notebook section

Fix Week 8 Lab note mistake

---

docs/es/README-ES.md
docs/es/week01/01-2.md

Updated `README-ES.md` with Victor Peñalosa review.
Also added commented original README, with flags.
Q: Should I add a flag for the original (English) language? If so, which flag? USA ?

[ES] README-ES.md improved translation

---

docs/ko/week03/03-2.md

initial translation of 03-2.md in Korean

[KR]03-2.md initial translation

---

README.md
docs/it/README-IT.md
docs/ko/README-KO.md
docs/zh/README-ZH.md

Added English flag to README.md.
Added all flags to ZH-KO-IT readmes.

[EN-ZH-KO-IT] Added missing flags

---

docs/ko/week02/02-2.md

[KR]02-2.md Initial translation

---

docs/ko/week02/02-2.md

[KR] Fix the typo on 02-2.md

---

docs/ko/week02/02-2.md

Didn`t apply the last review on previous PR.

[KR] 02-2.md PR for last review

---

docs/es/week05/05-2.md
docs/es/week05/05-3.md

Mostly all know words and terms. Please review. Thanks. Mauricio

[ES] Translation of 05-2.md and 05-3.md.

---

10-autoencoder.ipynb
docs/en/week05/05-2.md

Corrected momentum update formula based on this [piazza discussion](https://piazza.com/class/k5spqaanqk51ks?cid=137)
Removed redundant img.requires_grad_() based on this [piazza discussion](https://piazza.com/class/k5spqaanqk51ks?cid=141)

Adam momentum update formula

---

docs/ko/week03/03-1.md

[KR]Fix syntax error

---

docs/_config.yml
docs/es/week02/02-3.md

Spanish translation of file 02-3.md

[ES] Translation of 02-3.md

---

docs/_config.yml

[KR] Update _config.yml 02-3.md

---

docs/es/week01/01-3.md
docs/es/week02/02-1.md
docs/es/week02/02.md

Translation ch 01-3.md to spanish

[ES] translation of 01-3.md

---

docs/zh/week03/03-2.md

03-2 translate

---

docs/en/week03/03-2.md

Changed wording so it's clear that the properties are specific to natural signals and not just multidimensional arrays.

small edit in scribe notes

---

docs/_config.yml
docs/es/week06/06.md

[ES] Translation of 06.md

---

docs/es/index.md
docs/it/index.md
docs/ko/index.md
docs/zh/index.md

@LecJackS I tried your fix but it doesn't work properly. Here's the actual fix.
You can test these things out in the future by installing [jekyll](https://jekyllrb.com/docs/installation/) and running `serve.sh` from the `docs` folder.

fix index links for all languages

---

docs/en/week12/12-3.md

Rendered the webpage from my forked repo and it looks good. Sorry for the many bugs -- first time using KateX!

fixing bugs

---

docs/_config.yml
docs/es/week06/06-2.md

[ES] Translation of 06-2.md

---

docs/_config.yml
docs/it/week07/07.md

Adding translated `week07/07.md` to Italian docs, and modified `_config.yaml` to reflect new structure.

[IT] Adding week 7 landing in Italian

---

docs/en/week12/12.md

added week12 summary

---

docs/en/week12/12-3.md

Added the missing section on the implementation details at the end of the key-value store.

Added implementation details to key-value store

---

10-autoencoder.ipynb

This occurs on machines with GPU

move the noise to device.

---

docs/en/week13/13-2.md

Moving the figures to their correct location

Minor changes in 13-2

---

docs/en/week14/14-3.md

Enumerating figures and fixing paths.

Week14 - 3: Fix figures

---

docs/_config.yml
docs/en/week05/05-2.md
docs/it/week08/08-1.md
docs/it/week08/08-2.md
docs/it/week08/08-3.md
docs/it/week08/08.md

This time with rebase
Note: unfortunately until mid-June I won't be able to contribute as regularly to the project as I did in the previous weeks.

[IT] Week 8 [2nd PR]

---

docs/it/week07/07-3.md

follows notes added with PR #327

[IT] update of 07-3 following #327

---

docs/tr/week03/03.md

Replaced 'transformasyon' with 'dönüşüm'  as the latter is shorter and more Turkish. Also  changed some minor words. Other than these, it was a fine translation !

[TR] Review for Translation of 03.md

---

docs/tr/week08/08-1.md

The changes here were discussed during #367 with @emirceyani

[TR] Review for the Translation of 08-1.md

---

docs/en/week04/04-1.md
docs/en/week09/09-1.md
docs/en/week09/09-2.md
docs/es/week04/04-1.md
docs/it/week04/04-1.md
docs/it/week09/09-1.md
docs/ko/week04/04-1.md
docs/tr/week09/09-2.md
docs/zh/week04/04-1.md

- Didn't realize week04 was only a lab
- week09 is properly attributed

[MISC] More attribution fixes

---

docs/tr/week08/08-2.md
docs/tr/week09/09-3.md

These were *not* discussed with the original translator @emirceyani, lines of interest (i.e. not typos);
- 31, "eniyileme (optimization)" clarification were given after a couple of uses of 'eniyileme' so I moved that next to the first occurrence
- 210, I found the original sentence hard to follow so added a bit of verbosity

[TR] Review for the Translation of 08-2.md

---

docs/tr/week09/09-3.md

The original translator is @emirceyani, review mostly consists of typo fixes

[TR] Review for the Translation of 09-3.md

---

docs/en/week02/02-1.md
docs/es/week02/02-1.md
docs/ko/week02/02-1.md
docs/zh/week02/02-1.md

> For any set of Samples $$S = \{(x[p],y[p])/p=0,1...P-1 \}$$
Here, '/' may be understood as a division sign. '|' is a better choice.
> For any set of Samples $$S = \{(x[p],y[p])|p=0,1...P-1 \}$$

02-1.md formula fix

---

docs/tr/week01/01-1.md

Thought be were not supposed to change the metadata during the first pass, sorry!

[TR] Add translation of the title

---

docs/tr/week08/08-3.md

Just small changes and replaced Fig with Şekil.

[TR] Review for the Translation of 08-3.md

---

docs/_config.yml
docs/tr/week05/05-1.md
docs/tr/week05/05.md

Turkish translation of 05.md and 05-1.md

[TR] translation of 05.md and 05-1.md

---

docs/zh/index.md

[zh]Update index.md

---

docs/tr/index.md

[TR] index.md

---

docs/tr/index.md

Weeks 10-11-12 added to the index

[TR] updating index.md 

---

docs/_config.yml
docs/tr/week05/05-2.md
docs/tr/week05/05-3.md

Turkish translation for 2nd and 3th part of the Optimization section.

[TR] translation of 05-2.md and 05-3.md

---

docs/_config.yml
docs/es/week08/08-1.md
docs/es/week08/08.md

Also added links to _config.yml

[ES] Translated 08 and 08-1

---

docs/en/week14/14-1.md

line18: systems can bee => systems can be
line29: larger for every correct answer => larger for every incorrect answer

[EN] Typo fix 14-1.md

---

docs/_config.yml
docs/it/week06/06-2.md
docs/it/week06/06-3.md

This PR completes the 06 week, adding the italian translation of 
- 06-2.md 
- 06-3.md (WIP, NB. figures and titles are complete, text is wip, due for tomorrow)

[IT] Translation of 06 

---

README.md
docs/es/README-ES.md
docs/it/README-IT.md
docs/ja/README-JA.md
docs/ko/README-KO.md
docs/tr/README-TR.md
docs/zh/README-ZH.md

- Add the link to `README-JA.md` in each README

[JA] Add README-JA.md

---

docs/tr/week03/03-1.md

Final edits for Turkish translation. Still not sure about the table as mentioned in #345.

[TR] Review for the Translation of 03-1.md

---

docs/_config.yml
docs/tr/week13/13-3.md
docs/tr/week13/13.md

Translation of 13-3.md. There's also 13.md(1 sentence missing though) but @mekici can still do it.

[TR] Translation of 13-3.md

---

docs/en/week14/14-1.md

line136 byy using -> by using
line 147 discrimitive -> discriminative

Typo fix 14-1.md

---

docs/en/week14/14-1.md

line 165 from of tensor->form of tensor

Fix typos 14-1.md

---

docs/en/week14/14-1.md

Fix minor typos 14-1.md

---

docs/en/week14/14-1.md

perception loss->perceptron loss
(I need to fix my Korean translation version too, as perception and perceptron are clearly different...)

another typo fix [EN]14-1.md

---

docs/en/week14/14-2.md

renongnition -> recognition
Every typo I fix is in Eng lecture note 
Hope you all stay safe!

Fix typo [EN]14-2.md

---

docs/es/week02/02-1.md
docs/es/week02/02.md

Fixed some typos and words that weren't translated. I also, changed certain technical terms so that they matched the ones mentioned in the Wiki.

[ES] Review of 02.md and 02-1.md

---

docs/en/week12/12-3.md

[EN]Fixing the English error of 12-3.md "latent representation of the a sequence of text"

[EN]Fixing the English error of 12-3.md " representation of the a"

---

15-transformer.ipynb

Fixing the comment about the size 15-Transformer.md

[Code]Fixing the comment about the size in 15-Transformer.md

---

15-transformer.ipynb

[Code]15-transformer.ipynb Possible Issue 

---

docs/_config.yml
docs/en/week11/11-1.md
docs/en/week13/13-2.md
docs/es/week11/11-1.md
docs/fr/week11/11-1.md
docs/it/week11/11-1.md
docs/tr/week11/11-1.md
docs/zh/week11/11-1.md

Fixes #510, tested locally and seems to work
The config.yml change is to build jekyll correctly, I have a new setup and it doesn't seem to build without this line. It doesn't seem to affect how the page is displayed.

Fixes #510

---

docs/_config.yml
docs/en/week13/13.md
docs/es/week13/13-1.md
docs/es/week13/13.md

Spanish translations of 13 and 13-1 files.

[ES] Translation of 13.md and 13-1.md

---

docs/en/week14/14-3.md

Addressing content issue Fig 9 description of 14-3.md

[EN] Fix content issue in Fig 9 description of  14-3.md

---

docs/es/week09/09-3.md

Attached is the Spanish translation of the 9-3.md. Challenging translation due a very conceptual lecture with lots of terms. Used past translations as a reference.
It is ready for review.

[ES] Translation 09.3

---

docs/_config.yml
docs/es/week08/08-3.md

[ES] Translation of 08-3.md

---

docs/en/week06/lecture06.sbv
docs/en/week09/lecture09.sbv

Fixed the English captions for ch.6 and ch.09 videos.

English captions for ch.06 and ch.09 videos fixed.

---

16-gated_GCN.ipynb

[Notebook] typo 'what to backend to use'. 
Correction is what backend to use

[Notebook] typo 'what to backend to use'.

---

docs/zh/week13/13-3.md

Propagating the changes discussed [here](https://github.com/Atcold/pytorch-Deep-Learning/pull/576)

[ZH] 13-3: Propagating fix to English latex

---

docs/zh/week13/13-3.md

https://github.com/Atcold/pytorch-Deep-Learning/issues/618
This Pull request should be closed. I tried to fix the issue for https://github.com/Atcold/pytorch-Deep-Learning/issues/618
by replacing the latex form the English file. But it looks like the GitHub thinks the latex is the same as the English version. I added a space to make GitHub thinks they are different. If after pulling this requestion and shows the issue is not fixed. It means the issue is not in the translated Chinese file.

[ZH] Fixing 13-3.

---

docs/en/week03/lecture03.sbv

The auto generated captions were a good starting point but there were a lot of things to correct, particularly for technical terms (e.g., the words "convolution", "convolutional" were almost always detected as "commercial" or something else)
I added punctuation as well where I thought necessary.
One thing that's missing, but which implies a lot more work, is to ensure that every caption is small enough to fit in a line of roughly 50 characters (that's what some closed captioning guidelines suggest, anyway)
I reviewed the result using [YouTube's editor](https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=FW5gFiJb-ig&lang=en&bl=vmp&ui=hd&ref=player&tab=captions&noauto=yes&o=U&ar=1601048093076&new=yes&captions-r=1) (which is closing very soon for the community 😞) and it seemed …

[ES] Reviews and edits English captions - Week 3

---

docs/en/week07/lecture07.sbv

Edited English Video Caption for Lecture 07
Editor: Anis Farshian

Edited English Video Caption-Lecture07

---

docs/en/week03/practicum03.sbv

Hi @Atcold, I copy and pasted the entire revised `.sbv` with previous.

Revised practicum03.sbv English captions

---

docs/tr/week14/14-1.md

Corrections in grammar and punctuation. Also, I translated some parts which weren't translated or translated insufficiently. Made some parts easier to understand.

[TR] Update 14-1.md

---

docs/en/week02/practicum02.sbv

Edit English caption of practicum02.sbv
I edited this caption and It is reviewed by @miladnouriezade before, we checked it in slack.

[EN] Edit English caption of practicum02.sbv

---

docs/en/week01/practicum01.sbv
docs/en/week08/lecture08.sbv

Lecture 08 video caption has been edited.

[EN] Lecture 08 video caption

---

docs/_config.yml
docs/ar/week05/05-3.md

[AR] Translation of 05-3.md 

---

docs/en/week04/practicum04.sbv

Complete revision of English captions for practicum04

Revised English captions practicum04

---

docs/_config.yml
docs/fa/week09/09-1.md

Please check `_config.yml` in `docs` directory, one of the files from week 3 is under week 6, in line 580.

[FA] Translation of 09-1.md

---

docs/fr/index.md
docs/fr/week13/13-1.md
docs/fr/week13/13-2.md
docs/fr/week13/13-3.md
docs/fr/week14/14-2.md
docs/ko/week13/13-1.md
docs/ko/week13/13-2.md

I was optimistic that my previous PR would be the last. Again some corrections.
While checking the rendering on the site, I realized that for the 13-1 and 13-2 files, two English flag files were proposed.
I proposed a correction to fix that.

[FR] Few markdown corrections

---

docs/_config.yml
docs/en/week12/12-1.md
docs/en/week12/12.md
docs/es/week12/12-1.md
docs/es/week12/12.md

:neckbeard: :neckbeard: :neckbeard:

[ES] Translate 12, 12-1

---

docs/en/week01/practicum01.sbv
docs/en/week08/lecture08.sbv
docs/en/week08/practicum08.sbv

You're super cute, and it's so distracting for those who're watching the video of your class ;)
I even think the subtitle auto-generator was distracted as the subtitle was full of mistakes!

[EN] Editing practicum captions 08

---

docs/en/week12/lecture12.sbv

words that were unrecognizable after 3,4 times of listening with different playback speeds are replaced with [inaudible] tag.

[EN] Captions of lecture 12

---

docs/en/week10/10-3.md
docs/it/week10/10-3.md

As a reference to issue #493, I added the caption to Fig. 7 to both IT and EN files.
Please approve this PR so that I can ask the regional channels to translate the caption.
Thanks!

10-3: added caption for EN and IT Fig. 7

---

docs/en/week15/15-2.md
docs/en/week15/15.md
docs/index.md

- Change $y$ into $\vect{y}$
- Change $dz$ into $\mathrm{d}$
- Regularize format using \cdot, \text and \texttt
- Change Image Sizes to make thing clear
- Update Index.md and 15.md

Modified commit to week15-2 materials

---

docs/ja/README-JA.md

[JA] Fix typo README-JA.md

---

08-seq_classification.ipynb

@Atcold looks like `model` is not moved to the `device` in `train_and_test`
PS: tested locally and on colab

Fix 08-seq_classification.ipynb to work on CUDA

---

docs/en/week10/lecture10.sbv

There were 4 lines I wasn't so sure about, which I marked as "(?)" on the text, for lines. Please check lines:
- 4334
- 5012
- 7503
- 7545

[EN] Lecture10

---

docs/en/week11/lecture11.sbv

I corrected auto-generated captions to make the content more understandable by re-captioning, but there are some words that I don't understand what speakers meant. I marked them in the subtitle by putting three question marks (???).
In some places, I am confused between "some" and "sum", or between "path" and "pass". So I write them somewhere "sum/some".
Is there anyone to review that?

Re-captioning Lecture11.sbv

---

02-space_stretching.ipynb

Update 02-space_streching: fix code

---

docs/ar/week13/13-1.md
docs/en/week13/13-1.md
docs/es/week13/13-1.md
docs/fa/week13/13-1.md
docs/fr/week13/13-1.md
docs/ko/week13/13-1.md
docs/zh/week13/13-1.md

- fix typos in 13-1 the definition of convolution
- #678

Fix typos in 13-1 the definition of convolution

---

docs/en/week10/practicum10.sbv

English captions reviewed for Practicum 10.

[EN] Updated practicum 10

---

docs/_config.yml
docs/ko/week06/06-3.md
docs/ko/week08/08-3.md

Bug fix
- `06-03.md` broken on the website
_config.yml
- Updated missing files on week 10, 11, 13

[KR] Fixed some bugs, Updated _config.yml

---

docs/ko/week07/07.md
docs/ko/week13/13-1.md
docs/ko/week13/13-2.md

- Translated Untranslated Titles
- Terms unification

[KR] Fixed Titles in Korean

---

docs/en/week14/14-1.md

Figure name fix [EN]14-1.md

---

docs/vi/index.md

Hi Sir,
I corrected some error about typing in my updated contents.
Please check it for me.
Best wishes

[VI] Update index.md

---

docs/vi/week01/01-2.md

Hi Sir,
I corrected some error about typing in my updated contents.
Please check it for me.
Best wishes

[VI] Update 01-2.md

---

docs/vi/week01/01-3.md

Hi Sir,
I corrected some error about typing in my updated contents.
Please check it for me.
Best wishes

[VI] Update 01-3.md

---

docs/ja/index.md

Disclaimer partially rewritten for Japanese translation

[JA] Add week 13-15 and #639 translation

---

docs/en/week14/practicum14.sbv
docs/en/week15/practicum15A.sbv
docs/en/week15/practicum15B.sbv

[EN] Fix timers

---

11-VAE.ipynb

Added a` beta = 1` term to the `loss_function()` module. Beta can be set to whatever your heart desires, just know what this may imply for your model!

added beta term in 11-VAE

---

docs/en/week08/08-1.md

The original phrase "to a certain extend" should be "to a certain extent".

week 08/08-1.md: "to a certain extend"

---

docs/_config.yml
docs/bn/week02/02-2.md
docs/bn/week02/02-3.md

I've translated the week 2's 02-3.md file which is the last lecture file of week 2. Let me know if any changes need to be done.
Thanks

[BN] Translation of week02-3

---

docs/en/week11/11-2.md
docs/en/week15/15-2.md
docs/es/week11/11-2.md
docs/fr/week11/11-2.md
docs/ja/week11/11-2.md
docs/ko/week11/11-2.md
docs/tr/week11/11-2.md
docs/zh/week11/11-2.md

[DLSP21] Corrected equations in 11-2.md and deleted an inconsistent line  "Covered in section 2", but there was no section 2 on the page 15-2.md

[DLSP21] Update 11-2.md and 15-2.md

---

docs/fr/week15/15-1.md
docs/fr/week15/15-2.md
docs/fr/week15/15.md

Some markdown corrections. 
DeepL does not translate markdown anymore, I forgot that it was not the case last December :/

[FR] Corrections week 15

---

docs/ko/week13/13-3.md

updated the untranslated sentence:
`update_all(message_func, reduce_func)` sends messages through all edges and updates all nodes.

[KO] Add missing line for 13-3.md

---

docs/en/week07/07-3.md
docs/en/week11/11-2.md

Here the instructions is confusing, do is a variable that refers to the dropout layers, should specify in the code.

[DLFL21] Update 07-3.md

---

01-tensor_tutorial.ipynb

Hi Alfredo, 
Just started a hands-on on these notebooks. Came across this minor fix. Please have a look.
Thanks!

Minor fix in 01-tensor_tutorial.ipynb

---

docs/fr/faq.md

Hi @Atcold 
A little update after the translation of the 2021 edition.

[FR] Update FAQ

---

09-echo_data.ipynb

Test accuracy was not calculated correctly (always showed 0)

[09-echo-data.ipnb] fix wrong accuracy

---

09-echo_data.ipynb

* Add comments to explain that successive batches are not independent.
* Reset hidden state whenever EchoData state is reset.
* Expand the final "example" section to make it easier to read out when the model is correct.
* Use a fixed numpy seed for reproducibility.

[DLFL22] Clarify data "dependencies" in 09-echo_data.

---

docs/en/week07/07-1.md

"More fluctate" is somewhat difficult to parse.

[DLFL22] Rephrase \beta description in week 7 

---

01-tensor_tutorial.ipynb

essentiall -> essentially
two tensor -> two tensors

Two minor typos
