Atcold/NYU-DLSP20

README.md, apt.txt, environment.yml
Hi @Atcold. I was recently recommending your minicourse but I saw that as the result of recent course development the Binder for it is broken. Specifically, `torchvision` and `torchtext` are now used and are not part of the current `environment.yml`. In addition, in Notebook 10 `opencv` is used. In the notebook you install it in the environment using Jupyter shell magics, but this can't be done in Binder as the user doesn't have access to `conda` once they are in the built image. To fix this `opencv` is added to `environment.yml` and an `apt.txt` file is added which contains `libgl1-mesa-glx` for [Binder to install with apt-get](https://mybinder.readthedocs.io/en/latest/config_files.html#apt-txt-install-packages-with-apt-get) to provide some of the OS libraries that `opencv` needs.
Please …
=> Fix binder support by adding torchvision, torchtest, and opencv to environment.yml

02-space_stretching.ipynb
For linear transformation, we should actually do 
`Y = X* W^T` rather than `Y = X*W` considering we want to perform linear transformation `W`.
If we want to perform linear transformation `W^T`, then we will need to change `svd(W)` to `svd(W^T)`.
=> changed W to W transpose

14-truck_backer-upper.ipynb
Hi! I have modified the test loss calculation in 14-truck_backer-upper to correctly compute the test loss, and here is a pull request! Thank you!
=> Fixed test loss calculation bug

01-tensor_tutorial.ipynb, 02-space_stretching.ipynb, 03-autograd_tutorial.ipynb, 04-spiral_classification.ipynb, 05-regression.ipynb, 06-convnet.ipynb, 07-listening_to_kernels.ipynb, 08-seq_classification.ipynb, 09-echo_data.ipynb, 10-autoencoder.ipynb, 11-VAE.ipynb, 12-regularization.ipynb, 13-bayesian_nn.ipynb, 14-truck_backer-upper.ipynb, README.md, environment.yml
This:
* Moves PyTorch from 0.4 to 1.1 (one tiny code change)
* Moves Python from 3.6 to 3.7 (no changes to code, just env)
* Moves 1-2 requirements out of notebooks and into environment (potential nasty scipy pip install from librosa avoided!)
* Uses conda kernels so the correct environment kernel is available (all notebooks rerun to pick up proper kernel)
* Adds JuptyerLab (not required, but nice) - the interactive backend in the final notebook is still best in the classic interface. Try out built-in dark mode!
All notebooks seem to run (except noted minor issue with JupyterLab)
=> Updates to current packages

.gitignore, .gitmodules, 404.html, README.md, _config.yml, _layouts, chapters/01-1.md, chapters/01-2.md, chapters/01.md, chapters/02.md, extra/plot_lib.py, index.md, static
Hey - I eventually decided to just pull out the mdbook theme: I liked it a lot and it was nice to have it not be built. I have an example of the site in: https://ebetica.github.io/pytorch-Deep-Learning-Minicourse/chapters/01/
Check it out and let me know if you like it. The theme changing doesn't quite work (you have to refresh the page), but can fix it later. Katex works to write markdown, and you do not have to build the website. The sidebar structure is defined in _config.yml.
Developing locally is as simple as installing jekyll
```
gem install jekyll
```
and serving with
```
jekyll s --trace --baseurl ''
```
=> mdbook themed website for class notes

01-tensor_tutorial.ipynb
Modified the link in the "tensor_tutorial" notebook to point to the latest (stable) version of PyTorch docs.
=> Update the link to PyTorch documentation

environment.yml
This fixes the error produced by the CNN notebook when importing `torchvision`.
Apparently, `pillow` version 7.0 (latest) had some breaking changes, which were fixed in `torchvision` version 0.5 - more info here - https://github.com/pytorch/vision/pull/1501
The (probable) solution was to either downgrade `pillow` or update `torchvision` (and therefore `pytorch`).
=> Updated environment.yml to fix (potential) versioning issue

docs/README.md, docs/chapters/01-3.md, docs/chapters/02-3.md, docs/index.md
Some of the old links were working fine (the ones that directly pointed to a resource in the repository).
Some were not (the ones that pointed to the course website).
Updated all (hopefully!) to point to the new repository/site.
=> Updating links to be consistent with the repository rebranding

docs/chapters/05-2.md
As discussed, the fixes to not break the website and make it look terrible. The one noteworthy thing I want to comment on is that image 3c was having some CSS issues where despite having `width=200px` **and the exact same image size as the other two images**, it would display at ~181px width. I changed the width accordingly to make it consistent with the others.
I've tested out the website locally and it looks fine now, but let me know if I missed anything. Thanks for your patience!
=> Fix chapter 5-2 docs

docs/en/about.md, docs/en/index.md, docs/en/week01/01-3.md, docs/en/week02/02-1.md, docs/en/week02/02-2.md, docs/en/week02/02-3.md, docs/en/week03/03-1.md, docs/en/week03/03-2.md, docs/en/week03/03-3.md, docs/en/week04/04-1.md, docs/en/week05/05-1.md, docs/en/week05/05-2.md, docs/en/week05/05-3.md, docs/zh/week01/01-3.md
It turns out in Jekyll, you should use the link tag {% link path/to/file %} to generate
proper permalinks.
Here's the regex:
```
for f in $(fd '.md'); do sd '([^"(]*.png)' '{% link $1 %}' "$f"; done
```
=> Fix bug with images displaying on the website

docs/en/week02/02-3.md
I find the use of symbols and terms confusing in the section.
1. "* $\boldsymbol c$  and $\boldsymbol Y$ are both vectors that represent class labels for each of the $$\mathbf m$$ data points. In the example above, there are $$3$$ distinct classes." -- I think Y should be a matrix instead of a vector.
2. "**However, it is not true that** $$\mathbf Y \in \R^{m \times 1}$$" -- Here, Y refers to the same matrix above. IMO, it should have the same typeface `\boldsymbol`.
3. "with the $$i$$-th element of the $\boldsymbol Y $ vector set to $\mathbf 1$" -- Y is used again but as a vector, I think it should be `$\boldsymbol y^{(i)} $` according to the figure.
=> Change terms and symbols in "Training data"

docs/en/week05/05-2.md
The website was displaying "Vert" instead of || due to a latex error which should be fixed now.
=> Fixing vert bar latex error

docs/_config.yml
The bug is that the default Markdown parser actually does some
pre-processing of the display mode _only_ in a weird way that
made macros not apply. By disabling that, it behaves as expected.
=> Fix macros for display mode

docs/en/week05/05.md
The word `covergence` seems like a typo. Is it `convergence`?
=> Fix typo in Week 5 documentation

docs/en/week11/11-3.md
- Equations were not rendering on the website correctly. Changed the latex formatting.
- Changed the captions of the figures.
- Handled grammar related issues.
=> 11.3 Scribe - grammar and formatting issues fixed

docs/_config.yml, docs/en/week06/06-3.md, docs/es/week01/01-3.md, docs/es/week06/06-3.md
**[ES]**
Revised and corrected several typos and spelling errors in 01-3.
Translated 06.03 to Spanish.
**[EN]**
While doing it, found some typos on `/en/week06/06-3.md`, one latex typo, one missing latex, and two diagrams in inverse order ( :O and :| before the simple RNN).
=> [ES+EN] Translation 06-3, Review 01-3, EN Typos

15-transformer.ipynb
Just a quick fix on `idx` when playing around, otherwise the `acc` can be >1 (noticed this when overfitting the same small batch)
=> FIX idx otherwise acc>1

docs/en/week14/14-2.md
Q: How may hinge be better than NLL loss?
A: Hinge is better than NLL becuase **NLL** will try to push the difference between the correct answer and other answers to infinity, whereas hinge only wants to make it larger than some value (the margin m).
=> Fixing content issue in line55 of [EN] 14-2.md

docs/_config.yml, docs/es/week12/12-2.md
**Let's keep an eye on the associated videos** 
"**beam search**" --> here "búsqueda por haces" [https://www.youtube.com/watch?v=6D4EWKJgNn0&t=2732s]
"**traducción inversa**" [https://www.youtube.com/watch?v=6D4EWKJgNn0&t=3811s]
"**entrenamiento previo para NLP**" [https://www.youtube.com/watch?v=6D4EWKJgNn0&t=4963s]
=> [ES] Spanish translation week 12, section 2

docs/en/week13/13-3.md
The formula wasn't correctly rendered:
Before fix:
After fix:
I haven't checked the rest of the translations, but since the English one wasn't fixed maybe the rest do have this problem as well.
@Atcold
=> [EN] Fixed formula in English documents for chapter 13-3, Notation section.

docs/tr/week13/13-3.md
Propagating the changes made [here](https://github.com/Atcold/pytorch-Deep-Learning/pull/576)
The translation is wrong (there is English text) nearby my changes by the way:
Çizgemizde $v_{j}$, **which is comprised of** $\boldsymbol{x}\_j$ and $\boldsymbol{h}\_j$.
=> [TR] 13-3: propagating fix to English latex

docs/zh/week13/13-2.md
Issues:
I forgot to comment out some English words.
The "[基準化分析法圖形神經網絡](https://arxiv.org/pdf/2003.00982.pdf/)" shows the code rather than the link and words.
I see ### and ** often do not work in Chinese. I will see what we will have after this pull request.
=> [ZH] Fixing some issue on 13-2

docs/sr/README-SR.md, docs/sr/index.md
Hi Alfredo,
Here's a few minor corrections to the Serbian language landing page.
I'd like to leave a few remarks which we may wish to resolve before digging deeper:
- I think `RS` is a better choice than `SR`, given that the country-code for `SR` is Suriname.
- Serbian is a bit peculiar in that we tend to explicitly write out the spelling of somebody's name, the way it would be pronounced, even if they're of foreign origin. Hence, your name would be "Alfredo Kancijani", and NYU would be "Njujorški Univerzitet". Do you think we should go forward with such a convention?
Cheers,
Petar
=> [SR] Minor fixes + remarks about Serbian translation

docs/en/week02/02-2.md
From "Delving Deep into Rectifiers: Surpassing Human-Level Performance on ImageNet Classification",  Kaiming He et al. 2015.
Equations (10) and (14).
=> [EN] Possible error in lecture 2.2 - Kaiming initialization

docs/_config.yml, docs/pt/week02/02-1.md, docs/pt/week02/02-2.md, docs/pt/week02/02-3.md, docs/pt/week02/02.md
Notes about the translation
I maintained the English blocks in the source as the other versions but sliced them into bigger blocks by topic, I think it facilitates the translation.
I always used the English material as the primary source, in sentences where the translation to Portuguese didn't fully express the final meaning of the source material, I relied on the Spanish version (a version with more contributors and a mature version I think) just for that word to decide to translate or not.
For an example of a not translated term, in the 02-1 after the "Nash Equilibria" the acronym "GAN" (or generative adversarial network) is not translated in Spanish and I didn't translate either, because if you look up this acronym on the Portuguese Google, you will not find the correct explanation …
=> [PT] Portuguese translation of the second week of the course

12-regularization.ipynb
By TorchText 0.9.0 Release the `torchtext.data.Field` has changed to  `torchtext.legacy.data.Field`.
=> in compliance with Torchtext >= 0.9.0

res/sequential_tasks.py
I made changes to the description of the sequence in TemporalOrderExp6aSequence class to match the one described in 08-seq_classification.ipynb
=> corrected TemporalOrderExp6aSequence docstring

docs/en/faq.md, docs/fr/faq.md
Hi,
A tiny PR to fix the BibTex. 
The double brace displays well in markdown but not on the site. 
I'm reducing it to a single brace to fix the problem.
For French, there is also a display problem in the FAQ. Everything is ok when I preview the markdown file, but it displays badly once on the site.
This PR is trying to fix it but I'm not sure it will work. I don't understand where the problem comes from.
@Atcold, should we also add these "Foreword, FAQ and disclamer" pages for the 2021 edition?
=> Fix BibTex

docs/ja/week05/05-1.md
https://atcold.github.io/pytorch-Deep-Learning/ja/week05/05-1/
The closing bold tag (`</b>`) at caption of figure 1 is commented out, so all following elements are children of that. Because of this, markdown is not working.
=> [JA] fix-week-05-1

16-gated_GCN.ipynb
batch_scores = model(batch_graphs, **batch_X, batch_E**, batch_snorm_n, batch_snorm_e)
print(batch_scores.size())
batch_labels = batch_labels
print(f'accuracy: {accuracy(batch_scores, batch_labels)}')
torch.Size([10, 8])
accuracy: 10
=> [DLSP22] Update 16-gated_GCN.ipynb

docs/bn/week11/11-2.md, docs/en/week11/11-2.md, docs/es/week11/11-2.md, docs/fr/week11/11-2.md, docs/it/week11/11-2.md, docs/ja/week11/11-2.md, docs/ko/week11/11-2.md, docs/tr/week11/11-2.md, docs/zh/week11/11-2.md
Fixed a small mistake in the hinge loss equation in 11-2 -- the subtraction of the offending example's energy was outside of the max operator, where it should be inside -- see the table provided later in 11.2, or slide 19 here: https://cs.nyu.edu/~yann/talks/lecun-20041200-ebm-whistler.pdf
=> Fixed the hinge loss equation

docs/en/week09/09-1.md
Changed "you are start" to "you start".
"You are start" is grammatically wrong. The correct options are "you are starting" or "you start". But, the rest of the sentence is not using present continuous, so I chose to go with "you start".
This is grammatically correct, and in coherence with the rest of the sentence.
```md
--- You are start
+++ You start
```
=> Minor grammar correction - Update 09-1.md

docs/en/week09/09-1.md
I am quite sure that Yann LeCun talked about lateral inhibition and "natural inhibition" wasn't mentioned.
So, I changed "natural inhibition" to "lateral inhibition" because that is what is being discussed here. It is also clear from the context.
=> minor typo correction - changed natural inhibition to lateral inhibition - Update 09-1.md
